services:
  - type: web
    name: raventattooostudio
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    autoDeploy: true
